description: Publish a release of the project
executor: default
steps:
  - aws-cli/install
  - checkout
  - conditional-cancel:
      cancel_if_tag_in_commit: "[skip publish]"
  - poetry-configure
  - run: poetry install
  - run: poetry build
# TODO: For some reason we are getting 404s here - comment out to keep moving
#  - github-release
  - run: poetry publish
